'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AE_Ground.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ActionEntryLogoLM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActionEntryLogoLM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ActionEntryNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActionEntryNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AE_DK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AE_DK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AE_LT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AE_LT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AE_LT_2_48x48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AE_LT_2_48x48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AE_Main() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AE_Main", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property aeLogoNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aeLogoNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aeWhiteShadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aeWhiteShadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowsTransferBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowsTransferBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ATM_Logo_SEPARATED2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ATM_Logo_SEPARATED2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BarGraph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarGraph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property barGraphSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barGraphSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CautionBoardInterstate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CautionBoardInterstate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cautionSawHorse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cautionSawHorse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clock_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clockBlueSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clockBlueSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clockLightBlueSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clockLightBlueSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer_on_fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_on_fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dataSyncBtnImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dataSyncBtnImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downloadImages() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downloadImages", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dp2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dp2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dpInputOutput() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dpInputOutput", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EarthUploadNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EarthUploadNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gears2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gears3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gearsBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gearsBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gearsBrushedAlum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gearsBrushedAlum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gearsLightBlueSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gearsLightBlueSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GearsWindow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GearsWindow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GrayFade_UPRIGHT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GrayFade_UPRIGHT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property homeBlueSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homeBlueSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property homeGreenSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homeGreenSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property homeTitleBar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homeTitleBar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property homeTitleBar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homeTitleBar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageResizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageResizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesCategory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesCategory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InfoIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InfoIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property legend3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legend3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LightBluePipeFade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LightBluePipeFade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property locationbar_erase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("locationbar_erase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manEntry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manEntry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manualEntryBlueM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manualEntryBlueM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manualEntryGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manualEntryGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property none() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("none", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property onOffRedSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("onOffRedSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picMountainSky() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picMountainSky", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picsCameraSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picsCameraSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picsCameraSmaller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picsCameraSmaller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property progressTitleBar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressTitleBar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property progressTitleBar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressTitleBar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property puzzlePieceBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puzzlePieceBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refreshSilver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshSilver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sateliteDish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sateliteDish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sateliteDishsMALL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sateliteDishsMALL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SatelliteBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SatelliteBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SilverBrushedHorizontal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SilverBrushedHorizontal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property submitDataSync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("submitDataSync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property submitPics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("submitPics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property timeCalendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("timeCalendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TimeClock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TimeClock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transferImages() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transferImages", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transferImages2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transferImages2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UnderConstructionStripes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnderConstructionStripes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Upload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Upload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uploadImages() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uploadImages", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uploadRSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uploadRSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property utiltyHit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("utiltyHit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
