'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ae_UserID() As Integer
            Get
                Return CType(Me("ae_UserID"),Integer)
            End Get
            Set
                Me("ae_UserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_CurrentJob() As String
            Get
                Return CType(Me("ae_CurrentJob"),String)
            End Get
            Set
                Me("ae_CurrentJob") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\ActionEntry.mdb")>  _
        Public ReadOnly Property ActionEntryConnectionString() As String
            Get
                Return CType(Me("ActionEntryConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_DisplayName() As String
            Get
                Return CType(Me("ae_DisplayName"),String)
            End Get
            Set
                Me("ae_DisplayName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_PayItemsFilter() As String
            Get
                Return CType(Me("ae_PayItemsFilter"),String)
            End Get
            Set
                Me("ae_PayItemsFilter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_UserCred() As String
            Get
                Return CType(Me("ae_UserCred"),String)
            End Get
            Set
                Me("ae_UserCred") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ae_RetainUser() As Boolean
            Get
                Return CType(Me("ae_RetainUser"),Boolean)
            End Get
            Set
                Me("ae_RetainUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\ActionTraffic.mdb")>  _
        Public ReadOnly Property ATMConnectionString() As String
            Get
                Return CType(Me("ATMConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_ImagePath() As String
            Get
                Return CType(Me("ae_ImagePath"),String)
            End Get
            Set
                Me("ae_ImagePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ae_signHeightMin() As Double
            Get
                Return CType(Me("ae_signHeightMin"),Double)
            End Get
            Set
                Me("ae_signHeightMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ae_ColumnLeftMin() As Double
            Get
                Return CType(Me("ae_ColumnLeftMin"),Double)
            End Get
            Set
                Me("ae_ColumnLeftMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ae_ColumnRightMin() As Double
            Get
                Return CType(Me("ae_ColumnRightMin"),Double)
            End Get
            Set
                Me("ae_ColumnRightMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_AppPath() As String
            Get
                Return CType(Me("ae_AppPath"),String)
            End Get
            Set
                Me("ae_AppPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_DataSyncPath() As String
            Get
                Return CType(Me("ae_DataSyncPath"),String)
            End Get
            Set
                Me("ae_DataSyncPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FTPDataSyncURL() As String
            Get
                Return CType(Me("ae_FTPDataSyncURL"),String)
            End Get
            Set
                Me("ae_FTPDataSyncURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FTPuserName() As String
            Get
                Return CType(Me("ae_FTPuserName"),String)
            End Get
            Set
                Me("ae_FTPuserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FTPuserCred() As String
            Get
                Return CType(Me("ae_FTPuserCred"),String)
            End Get
            Set
                Me("ae_FTPuserCred") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ae_WorkingDate() As Date
            Get
                Return CType(Me("ae_WorkingDate"),Date)
            End Get
            Set
                Me("ae_WorkingDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_CurrDataSyncFileName() As String
            Get
                Return CType(Me("ae_CurrDataSyncFileName"),String)
            End Get
            Set
                Me("ae_CurrDataSyncFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ae_DataSyncComplete() As Boolean
            Get
                Return CType(Me("ae_DataSyncComplete"),Boolean)
            End Get
            Set
                Me("ae_DataSyncComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_DebugPath() As String
            Get
                Return CType(Me("ae_DebugPath"),String)
            End Get
            Set
                Me("ae_DebugPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FTPdeBugPath() As String
            Get
                Return CType(Me("ae_FTPdeBugPath"),String)
            End Get
            Set
                Me("ae_FTPdeBugPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_CurrentPLfileName() As String
            Get
                Return CType(Me("ae_CurrentPLfileName"),String)
            End Get
            Set
                Me("ae_CurrentPLfileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_DataSyncID() As String
            Get
                Return CType(Me("ae_DataSyncID"),String)
            End Get
            Set
                Me("ae_DataSyncID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0; Data Source=\\attermserv01\company data\Action\"& _ 
            "Action Traffic.mdb")>  _
        Public Property atmProductionConStr() As String
            Get
                Return CType(Me("atmProductionConStr"),String)
            End Get
            Set
                Me("atmProductionConStr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property atmServerDataSync() As String
            Get
                Return CType(Me("atmServerDataSync"),String)
            End Get
            Set
                Me("atmServerDataSync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FTPImageSyncURL() As String
            Get
                Return CType(Me("ae_FTPImageSyncURL"),String)
            End Get
            Set
                Me("ae_FTPImageSyncURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property atmLocalDataSync() As String
            Get
                Return CType(Me("atmLocalDataSync"),String)
            End Get
            Set
                Me("atmLocalDataSync") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0; Data Source=C:\ActionEntry\LocalDS\Action Traff"& _ 
            "ic.mdb")>  _
        Public ReadOnly Property atmLocalConStr() As String
            Get
                Return CType(Me("atmLocalConStr"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property atmImagesPath() As String
            Get
                Return CType(Me("atmImagesPath"),String)
            End Get
            Set
                Me("atmImagesPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property localImagesPath() As String
            Get
                Return CType(Me("localImagesPath"),String)
            End Get
            Set
                Me("localImagesPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_ImageDateFolder() As String
            Get
                Return CType(Me("ae_ImageDateFolder"),String)
            End Get
            Set
                Me("ae_ImageDateFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_TransferImagePath() As String
            Get
                Return CType(Me("ae_TransferImagePath"),String)
            End Get
            Set
                Me("ae_TransferImagePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_TransferDataSyncPath() As String
            Get
                Return CType(Me("ae_TransferDataSyncPath"),String)
            End Get
            Set
                Me("ae_TransferDataSyncPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_DownloadImagePath() As String
            Get
                Return CType(Me("ae_DownloadImagePath"),String)
            End Get
            Set
                Me("ae_DownloadImagePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_WarehouseXml() As String
            Get
                Return CType(Me("ae_WarehouseXml"),String)
            End Get
            Set
                Me("ae_WarehouseXml") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_TimeSheetTxtPath() As String
            Get
                Return CType(Me("ae_TimeSheetTxtPath"),String)
            End Get
            Set
                Me("ae_TimeSheetTxtPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_WarehouseTimeSheet() As String
            Get
                Return CType(Me("ae_WarehouseTimeSheet"),String)
            End Get
            Set
                Me("ae_WarehouseTimeSheet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_MailUserName() As String
            Get
                Return CType(Me("ae_MailUserName"),String)
            End Get
            Set
                Me("ae_MailUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_MailCred() As String
            Get
                Return CType(Me("ae_MailCred"),String)
            End Get
            Set
                Me("ae_MailCred") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FTProotSync() As String
            Get
                Return CType(Me("ae_FTProotSync"),String)
            End Get
            Set
                Me("ae_FTProotSync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_LocalRootSync() As String
            Get
                Return CType(Me("ae_LocalRootSync"),String)
            End Get
            Set
                Me("ae_LocalRootSync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ae_RootSyncDateTime() As Date
            Get
                Return CType(Me("ae_RootSyncDateTime"),Date)
            End Get
            Set
                Me("ae_RootSyncDateTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_TimeLocalPath() As String
            Get
                Return CType(Me("ae_TimeLocalPath"),String)
            End Get
            Set
                Me("ae_TimeLocalPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FtpTime() As String
            Get
                Return CType(Me("ae_FtpTime"),String)
            End Get
            Set
                Me("ae_FtpTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_ProductionConStr() As String
            Get
                Return CType(Me("ae_ProductionConStr"),String)
            End Get
            Set
                Me("ae_ProductionConStr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property atmServerWarehouseXmlPath() As String
            Get
                Return CType(Me("atmServerWarehouseXmlPath"),String)
            End Get
            Set
                Me("atmServerWarehouseXmlPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property am_NewMessagePath() As String
            Get
                Return CType(Me("am_NewMessagePath"),String)
            End Get
            Set
                Me("am_NewMessagePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property am_InBox() As String
            Get
                Return CType(Me("am_InBox"),String)
            End Get
            Set
                Me("am_InBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property am_OutBox() As String
            Get
                Return CType(Me("am_OutBox"),String)
            End Get
            Set
                Me("am_OutBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property am_FTPNewMessage() As String
            Get
                Return CType(Me("am_FTPNewMessage"),String)
            End Get
            Set
                Me("am_FTPNewMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property am_FTPArchive() As String
            Get
                Return CType(Me("am_FTPArchive"),String)
            End Get
            Set
                Me("am_FTPArchive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property am_Deleted() As String
            Get
                Return CType(Me("am_Deleted"),String)
            End Get
            Set
                Me("am_Deleted") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property am_Sent() As String
            Get
                Return CType(Me("am_Sent"),String)
            End Get
            Set
                Me("am_Sent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ae_SubmitSysInfo() As Boolean
            Get
                Return CType(Me("ae_SubmitSysInfo"),Boolean)
            End Get
            Set
                Me("ae_SubmitSysInfo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property at_CrewListFilter() As String
            Get
                Return CType(Me("at_CrewListFilter"),String)
            End Get
            Set
                Me("at_CrewListFilter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_WorkType() As String
            Get
                Return CType(Me("ae_WorkType"),String)
            End Get
            Set
                Me("ae_WorkType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ae_SilicaExposure() As Boolean
            Get
                Return CType(Me("ae_SilicaExposure"),Boolean)
            End Get
            Set
                Me("ae_SilicaExposure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ae_100AirMile() As Boolean
            Get
                Return CType(Me("ae_100AirMile"),Boolean)
            End Get
            Set
                Me("ae_100AirMile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property expDeclPath() As String
            Get
                Return CType(Me("expDeclPath"),String)
            End Get
            Set
                Me("expDeclPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property expDeclWarehousePath() As String
            Get
                Return CType(Me("expDeclWarehousePath"),String)
            End Get
            Set
                Me("expDeclWarehousePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ae_FTPexpDecl() As String
            Get
                Return CType(Me("ae_FTPexpDecl"),String)
            End Get
            Set
                Me("ae_FTPexpDecl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property aeDocumentsPath() As String
            Get
                Return CType(Me("aeDocumentsPath"),String)
            End Get
            Set
                Me("aeDocumentsPath") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AE_Ground.My.MySettings
            Get
                Return Global.AE_Ground.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
